### 1. What is a Python library? Why we use Python libraries?

* A Python library is a collection of pre-written code that you can use to perform common tasks, make programming easier, and reduce the amount of code you need to write. Libraries can include functions, classes, and modules that provide various functionalities, ranging from basic operations to complex tasks such as data manipulation, web development, machine learning, and more.

* We Use Python Libraries for several reasons like:

1. Code Reusability: Libraries allow you to reuse code written by others, saving time and effort in writing code from scratch
2. Efficiency: Libraries are often optimized for performance, making your programs faster and more efficient.
3. Ease of Use: Libraries provide a simple and standardized interface for complex tasks, making them easier to implement.
4. Community Support: Many libraries are maintained by the community, ensuring they are up-to-date, well-documented, and debugged.

### 2. What is the difference between Numpy array and List?

Python lists and NumPy arrays are both used to store collections of items, but they have significant differences in terms of functionality, performance, and usage. Here's a comparison of key aspects:

1. Data Types and Homogeneity:

Python List Can store elements of different data types (e.g., integers, floats, strings).
* Example: [1 , 2.5, "apple"] is a valid list.

NumPy Array Requires all elements to be of the same data type. This uniformity allows for optimized performance.
* Example: np.array([1, 2, 3]) creates an array of integers, while np.array([1.0, 2.5, 3.1]) creates an array of floats.

2. Performance and Efficiency

* Python List Generally slower for numerical operations because they are not optimized for arithmetic operations.They have overhead due to the dynamic type checking and flexibility.

* NumPy Array Much faster for numerical computations because they are implemented in C and use contiguous blocks of memory.Supports vectorized operations, which allow element-wise operations without explicit loops.

3. Functionality and Operations

* Python List Offers general-purpose functionality and flexibility.Limited built-in support for mathematical operations and advanced manipulations.
* NumPy Array Designed for scientific computing with extensive support for mathematical functions, linear algebra, Fourier transforms, and random number generation.Provides powerful broadcasting capabilities, which allow operations on arrays of different shapes.

4. Memory Consumption

* Python List Uses more memory because each element is an object, and there is overhead associated with storing type information and pointers.
* NumPy Array More memory-efficient as they store elements in a contiguous block of memory and use fixed-size data types.

5. Indexing and Slicing
* Python List Supports basic indexing and slicing but lacks advanced features like multi-dimensional indexing
* NumPy Array Supports multi-dimensional arrays (ndarrays) with advanced indexing and slicing capabilities.

6. Use Cases

* Python List Suitable for general-purpose programming where flexibility and heterogeneous data storage are needed.
* NumPy Array Ideal for numerical computations, data analysis, machine learning, and any scenario requiring efficient handling of large datasets.

### 3 Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
shape = arr.shape
size = arr.size
dimension = arr.ndim

shape, size, dimension

((3, 4), 12, 2)

### 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
arr1 = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
first_row = arr1[0]
first_row

array([1, 2, 3, 4])

### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [17]:
element = arr1[2,3]
element

12

#### 6. Write code to extract all odd-indexed elements from the given numpy array?

In [21]:
odd_indexed_elements = []

rows, cols = array.shape
for i in range(rows):
    for j in range(cols):
        if i % 2 != 0 or j % 2 != 0:
            odd_indexed_elements.append(array[i, j])

print(odd_indexed_elements)

[2, 4, 5, 6, 7, 8, 10, 12]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [22]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.65300707, 0.13446607, 0.31148503],
       [0.16975866, 0.76731406, 0.43902299],
       [0.90089872, 0.42637289, 0.50756195]])

### 8. Describe the difference between np.random.rand and np.random.randn?

The functions np.random.rand and np.random.randn from the NumPy library both generate arrays of random numbers, but they have different distributions for their generated numbers. Here's a detailed comparison of the two:
1. np.random.rand
* Description: Generates random numbers from a uniform distribution.
* Range: The values are in the range [0, 1).
* Distribution: Uniform distribution, meaning each number in the specified range is equally likely to be drawn.
* Usage: Useful when you need random samples from a uniform distribution.

2. np.random.randn
* Description: Generates random numbers from a standard normal (Gaussian) distribution.
* Range: The values can range from negative infinity to positive infinity, though most values will lie within a few standard deviations of the mean.
* Distribution: Normal distribution with mean 0 and standard deviation 1.
* Usage: Useful when you need random samples from a normal distribution.

### 9. Write co^e to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
expanded_array = np.expand_dims(arr1, axis = 1)
expanded_array

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [28]:
arr1.ndim

2

### 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

### 11. Consider the following matrix:
* Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
* Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

### Perform the following operation using Python
* Index wise multiplication



In [2]:
import numpy as np

In [5]:
arr_a =  np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr_b =  np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [6]:
arr_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr_a*arr_b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

*  Matrix multiplication

In [9]:
np.dot(arr_a,arr_b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

matrix multiplication is not possible because the number of columns in the first matrix must be equal to the number of rows in the second matrix. In this case, both matrices are 3x4, so they cannot be multiplied directly using traditional matrix multiplication rules.

* Add both the matrics

In [17]:
np.add(arr_a, arr_b)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

* Subtract matrix B from A

In [18]:
sub = np.subtract(arr_a, arr_b)

In [19]:
sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

* Divide Matrix B by A

In [20]:
np.divide(arr_a, arr_b)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 12.  Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the byteswap() function can be used to swap the byte order of an array. This function can be useful when dealing with data that has a different endianness than your system's native byte order.
for example:

In [22]:
import numpy as np

# Create an array with a specific dtype
arr = np.array([1, 256, 65536], dtype=np.int32)

print("Original array:")
print(arr)
print("Original byte order:")
print(arr.byteswap().newbyteorder())

# Swap the byte order
swapped_arr = arr.byteswap()

print("Array with swapped byte order:")
print(swapped_arr)
print("Swapped byte order:")
print(swapped_arr.newbyteorder())


Original array:
[    1   256 65536]
Original byte order:
[    1   256 65536]
Array with swapped byte order:
[16777216    65536      256]
Swapped byte order:
[    1   256 65536]


### 13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its utility for solving systems of linear equations, determining the singularity of a matrix, and for various other mathematical and computational applications.

### 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to reorganize the elements of an array to fit into a new shape specified by the user. for example:

In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 2 rows and 3 columns
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


### 15. What is broadcasting in Numpy?